# Site Settings
baseurl: "/startbootstrap"
url: http://tirelesswake.github.io
encoding: UTF-8

# Build Settings
markdown: kramdown
permalink: pretty

# Site Details
license: "Apache 2.0"
license-url: "https://github.com/IronSummitMedia/startbootstrap/blob/gh-pages/LICENSE"
author: "Start Bootstrap"

# Jekyll Redirect From Plugin for Redirects from Start Bootstrap Old Version
gems:
  - jekyll-redirect-from
